name: CI Workflow

on:
  # Also available on push/pull request to master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

      build_type:
        description: 'Type of build to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - incremental

      debug:
        description: 'Enable debug logging'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

      version_tag:
        description: 'Optional version tag (e.g., v1.2.3)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  # Uses the branch selected in GitHub UI

      - name: Show selected inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Build type: ${{ github.event.inputs.build_type }}"
          echo "Debug mode: ${{ github.event.inputs.debug }}"
          echo "Version tag: ${{ github.event.inputs.version_tag }}"

      - name: Conditional logic based on inputs
        run: |
          if [ "${{ github.event.inputs.debug }}" == "true" ]; then
            echo "🔍 Debug logging is enabled"
          fi

          if [ "${{ github.event.inputs.build_type }}" == "incremental" ]; then
            echo "🧱 Running an incremental build"
          else
            echo "🏗️ Running a full build"
          fi
